[package]
name = "rabbet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
itertools = "0.14.0"
once_cell = "1.21.3"
polars = { version = "0.35", features = ["lazy", "csv", "json", "parquet"] }
regex = "1.11.1"
termsize = "0.1"

[dev-dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
tempfile = "3.8"
