[package]
name = "rabbet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
polars = { version = "0.35", features = ["lazy", "csv", "json", "parquet"] }
termsize = "0.1"

[dev-dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }
tempfile = "3.8"
