[book]
authors = ["Rory Finnegan"]
language = "en"
src = "src"
title = "Rabbet"
description = "Documentation for Rabbet - CLI to simplify shell scripts and glue code operating on relational data"

[build]
build-dir = "book"

[output.html]
additional-css = ["./theme/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/rofinn/rabbet"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rofinn/rabbet/edit/main/docs/{path}"
site-url = "/rabbet/"
fold.enable = true
fold.level = 1
print.enable = true
copy-js = true
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
runnable = false

[output.html.highlight]
additional-languages = [
    "bash",
    "console",
    "shell",
    "zsh",
    "fish",
    "powershell",
    "dos",
    "dockerfile",
    "yaml",
    "toml",
]

[preprocessor.index]

[preprocessor.links]
