name: Run Fork PR Benchmarks

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  benchmark_fork_pr_branch:
    name: Run Fork PR Benchmarks
    # Only run for PRs from forks
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]

      - uses: Swatinem/rust-cache@v2 # zizmor: ignore[unpinned-uses]

      - name: Install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/latest/download/hyperfine_1.19.0_amd64.deb
          sudo dpkg -i hyperfine_1.19.0_amd64.deb

      # TODO: I'm not sure there is any point to the summary file?
      - name: Run benchmarks (without Bencher)
        run: |
          chmod +x scripts/benchmark
          # Run without bencher integration (no secrets available in fork PRs)
          ./scripts/benchmark > benchmark_output.txt 2>&1

          # Extract JSON results from the temp files created by the script
          mkdir -p benchmark_results
          cp /tmp/*_results.json benchmark_results/ 2>/dev/null || true

          # Create a summary file
          echo "Fork PR Benchmark Results" > benchmark_results/summary.txt
          echo "========================" >> benchmark_results/summary.txt
          tail -n 20 benchmark_output.txt >> benchmark_results/summary.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4 # zizmor: ignore[unpinned-uses]
        with:
          name: benchmark-results
          path: benchmark_results/

      - name: Upload PR event
        uses: actions/upload-artifact@v4 # zizmor: ignore[unpinned-uses]
        with:
          name: pr-event
          path: ${{ github.event_path }}
