name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

permissions: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - uses: taiki-e/install-action@v2 # zizmor: ignore[ref-confusion, unpinned-uses]
        with:
          tool: cargo-llvm-cov, cargo-nextest
      - uses: Swatinem/rust-cache@v2 # zizmor: ignore[unpinned-uses]
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - name: Test
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov report --lcov --output-path lcov.info
      - name: Coverage
        uses: codecov/codecov-action@v5 # zizmor: ignore[unpinned-uses]
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2 # zizmor: ignore[unpinned-uses]
        with:
          mdbook-version: "latest"
      - name: Build documentation
        run: mdbook build
      - name: Check for broken links
        run: |
          # Install linkchecker if needed
          sudo apt-get update && sudo apt-get install -y linkchecker || true
          # Run link checking on the built book (allow some common false positives)
          linkchecker book/ --ignore-url='^mailto:' --ignore-url='^https://github.com/.*/(issues|pull)' || true
