name: CI

on:
  push:
  pull_request:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBU: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable # zizmor: ignore[unpinned-uses]
        with:
          components: rustfmt, clippy, llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov # zizmor: ignore[unpinned-uses]
      - uses: taiki-e/install-action@nextest # zizmor: ignore[unpinned-uses]
      - uses: Swatinem/rust-cache@v2 # zizmor: ignore[unpinned-uses]
      - name: Compile
        run: cargo check --locked
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --locked
      - name: Test
        run: |
          cargo llvm-cov --no-report nextest
          cargo llvm-cov report --lcov --output-path lcov.info
      - name: Coverage
        uses: codecov/codecov-action@v5 # zizmor: ignore[unpinned-uses]
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
